[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "kindling-cli"
version = "0.6.6"
description = "Command-line tooling for Kindling"
authors = ["SEP Engineering <engineering@sep.com>"]
license = "MIT"
readme = "README.md"
packages = [
    {include = "kindling_cli", from = "."}
]

[tool.poetry.dependencies]
python = "^3.10"
click = ">=8.1.0"
pyyaml = ">=6.0"
kindling-sdk = ">=0.6.6"

[tool.poetry.scripts]
kindling = "kindling_cli.cli:main"
